### ISSUE TITLE
Extra quiz question at end of Git Basics Quiz

### ISSUE THREAD

**Issue by clarissajaime** [learn-co-curriculum/git-github-learn-quiz#12]
As a user, I want all of the questions to be displayed before the "submit" button. Or if it's an extra credit question, it should include a header that describes it as that. 

<img width="837" alt="screen shot 2018-03-25 at 8 43 45 pm" src="https://user-images.githubusercontent.com/5231109/37882033-6fea8156-306d-11e8-9212-ae2526df4ba3.png">

**Comment by sgharms** [comment]
@clarissajaime Wow, that is odd! It seems to be a bug in the Learn platform's formatting of quizzes. I'll open an issue with them but close this case.

💙 Flatiron Curriculum Team

**Comment by sgharms** [comment]
@clarissajaime 

OK I've gotten some clarification here. The SUBMIT button is designed for you to be able to SUBMIT that you've selected the multiple applicable checkboxes. I.e. trigger a "grade this response" action (or else how would the quiz know you were done choosing). I _think_ the confusion comes fro the fact that the word SUBMIT appears in the penultimate position on the screen and triggers the assumption "OH I'M AT THE END." Or, at the least it did for both you and I.

I've opened these as user experience bugs on the quiz product so hopefully I can fix this long term.

Best,

Steven @ Flatiron 💙
