### ISSUE TITLE
Check boxes in question 10 are unresponsive for me

### ISSUE THREAD

**Issue by amy-l-hedges** [learn-co-curriculum/git-github-learn-quiz#13]
Can't select any answers!

**Comment by drakeltheryuujin** [comment]
Hi @amy-l-hedges,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If this is still an issue and you can provide further detail about the steps required to reproduce the issue, I'd be happy to take a second look!

As always, thanks for contributing! 💙
