### ISSUE TITLE
Git & GitHub lessons lack efficacy at current position in curriculum

### ISSUE THREAD

**Issue by jebediahelliott** [learn-co-curriculum/git-github-learn-quiz#14]
Since the Git and GitHub lessons are designed to be used in conjunction with a local environment instead of the IDE I think they would be more effective if they were moved to the point in the curriculum where it is recommended to switch from IDE to local. I know that for me, the information will be a vague memory that needs revisited by the time I switch to a local. I hope you find this helpful.

Best,
Jeb

**Comment by cjbrock** [comment]
We're always working on the curriculum. This is helpful feedback and we'll take it into consideration as we make future updates. Thank you for taking your time to help us make Learn a better place.
